# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c978c9b3998350d9608c93cc1adf0a8a45ef8392ca1cc3cd3654094d17729c16e4be89ee1aab8380bfd3e0bcd9761f56e04a2ef065dbffa3a63fe80936399b59

test:
  secret_key_base: 4f242f2f70bd673626ce71fa0d9eb42fc4355c2be03eb4b46d51887d119a54dc08b3c11f4c4c9437b8403d0557ea5485833de0e9f379aa8986f87b2b6d50e4c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
